name: generate-and-upload-card

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *"

  # Permite executar o job manualmente
  workflow_dispatch:

  # Executa a cada push na branch master (ou altere para main se sua branch principal for main)
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github stats card
        uses: LuciNyan/pixel-profile/action@v1.0.0
        with:
          outputs: |
            dist/github-stats?username=Erickify&screen_effect=false&theme=fuji&dithering=true&hide=avatar
            dist/github-stats-dark?username=Erickify&screen_effect=true&pixelate_avatar=false

      # Publica os arquivos gerados na branch de saída (output)
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
